# Laser source properties:
#   wavelength: central wavelength, in nm
#   bandwidth:  bandwidth, in nm
#   stability:  long-term wavelength stability, in nm
#   intensity:  observed total intensity at sensor, in counts/s
#   imbalance:  power inconsistency between two arms
# Laser interference sensing model:
#   d_i = A_i * I_i + b_i, for i = 0,1,2,3.
#   d_0, d_1, d_2 and d_3 are ABCD samplings at four different phases.
#   A_i and b_i are amplitude and additive background correspondingly.
# ToF sensor properties:
#   precision:  ranging precision, in mm.

laser-int-r:
  wavelength: 633.0
  bandwidth: 0.1
  stability: 0.5
  intensity: 1e6
  imbalance: 1e-4
laser-int-g:
  wavelength: 532.0
  bandwidth: 0.1
  stability: 0.5
  intensity: 1e6
  imbalance: 1e-4
sensor-int:
  amplitude-stability: 0.01
  phase-stability: 0.01
  background: 1e2
sensor-tof:
  precision: 10.0
runtime:
  resolution: 1000