# Laser source properties:
#   wavelength:  central wavelength, in nm
#   bandwidth:   bandwidth (1-sigma), in nm
#   instability: long-term wavelength instability (1-sigma), in nm
#   intensity:   observed total intensity at sensor, in counts/s
#   imbalance:   power inconsistency between two arms
# Laser interference sensing model:
#   d_i = G_i * I_i + b_i, for i = 0,1,2,3.
#   d_0, d_1, d_2 and d_3 are ABCD samplings at four different phases.
#   G_i and b_i are gain factor and additive background correspondingly.
# ToF sensor properties:
#   precision:  ranging precision (1-sigma), in mm.

laser-int-r:
  wavelength: 532.0
  bandwidth: 1.0
  instability: 0.5
  intensity: 1e9
  imbalance: 1e-9
laser-int-g:
  wavelength: 635.0
  bandwidth: 1.0
  instability: 0.5
  intensity: 1e9
  imbalance: 1e-9
sensor-int:
  gain-deviation:  0.01
  phase-deviation: 0.01
  background: 1e2
sensor-tof:
  precision: 10.0
runtime:
  spectral-resolution: 100
  distance-resolution: 0.1
  parameter-resolution: 100
